"""This file contains metadata to help describe the featurizers.
"""

properties = {
    "3D-Descriptors": {
        "Asphericity": {
            "name": "asphericity",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Molecular asphericity",
        },
        "Eccentricity": {
            "name": "eccentricity",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Molecular eccentricity",
        },
        "InertialShapeFactor": {
            "name": "inertial_shape_factor",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Inertial shape factor",
        },
        "NPR1": {
            "name": "npr1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Normalized principal moments ratio 1 (=I1/I3)",
        },
        "NPR2": {
            "name": "npr2",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Normalized principal moments ratio 2 (=I2/I3)",
        },
    },
    "2D-Descriptors": {
        # Feature names are extracted from rdkit.Chem.Descriptors.descList
        "MaxEStateIndex": {
            "name": "max_e_state_index",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Maximum value of the electrotopological state atom index",
        },
        "MinEStateIndex": {
            "name": "min_e_state_index",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Minimum value of the electrotopological state atom index",
        },
        "MaxAbsEStateIndex": {
            "name": "max_abs_e_state_index",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": (
                "Maximum absolute value of the electrotopological state atom index"
            ),
        },
        "MinAbsEStateIndex": {
            "name": "min_abs_e_state_index",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": (
                "Minimum absolute value of the electrotopological state atom index"
            ),
        },
        "qed": {
            "name": "qed",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Quantitative estimation of drug-likeness",
        },
        "MolWt": {
            "name": "mol_wt",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Average molecular weight",
        },
        "HeavyAtomMolWt": {
            "name": "heavy_atom_mol_wt",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Average molecular weight ignoring hydrogens",
        },
        "ExactMolWt": {
            "name": "exact_mol_wt",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "The exact molecular weight",
        },
        "NumValenceElectrons": {
            "name": "num_valence_electrons",
            "dimensionality": "scalar",
            "type": "int",
            "units": "",
            "description": "The number of valence electrons in the molecule",
        },
        "NumRadicalElectrons": {
            "name": "num_radical_electrons",
            "dimensionality": "scalar",
            "type": "int",
            "units": "",
            "description": "The number of radical electrons in the molecule (regardless of their spin)",
        },
        "MaxPartialCharge": {
            "name": "max_partial_charge",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Maximum partial charge on the molecule",
        },
        "MinPartialCharge": {
            "name": "min_partial_charge",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Minimum partial charge on the molecule",
        },
        "MaxAbsPartialCharge": {
            "name": "max_abs_partial_charge",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Maximum absolute value of partial charge on the molecule",
        },
        "MinAbsPartialCharge": {
            "name": "min_abs_partial_charge",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Minimum absolute value of partial charge on the molecule",
        },
        "FpDensityMorgan1": {
            "name": "fp_density_morgan1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Morgan-1 density fingerprint",
        },
        "FpDensityMorgan2": {
            "name": "fp_density_morgan2",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Morgan-2 density fingerprint",
        },
        "FpDensityMorgan3": {
            "name": "fp_density_morgan3",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Morgan-3 density fingerprint",
        },
        "BCUT2D_MWHI": {
            "name": "bcut2d_mwhi",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_MWLOW": {
            "name": "bcut2d_mwlow",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_CHGHI": {
            "name": "bcut2d_chghi",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_CHGLO": {
            "name": "bcut2d_chglo",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_LOGPHI": {
            "name": "bcut2d_logphi",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_LOGPLOW": {
            "name": "bcut2d_logplow",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_LOGPLOW": {
            "name": "bcut2d_logplow",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_MRHI": {
            "name": "bcut2d_mrhi",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_MRLOW": {
            "name": "bcut2d_mrlow",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BalabanJ": {
            "name": "balaban_j",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Balaban's J value for a molecule",
        },
        "BertzCT": {
            "name": "bertz_ct",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Topological complexity index of a molecule",
        },
        "Chi0": {
            "name": "chi0",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-0 graph descriptor",
        },

    },
}
