"""This file contains metadata to help describe the featurizers.
"""

properties = {
    "3D-Descriptors": {
        "Asphericity": {
            "name": "asphericity",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Molecular asphericity",
        },
        "Eccentricity": {
            "name": "eccentricity",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Molecular eccentricity",
        },
        "InertialShapeFactor": {
            "name": "inertial_shape_factor",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Inertial shape factor",
        },
        "NPR1": {
            "name": "npr1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Normalized principal moments ratio 1 (=I1/I3)",
        },
        "NPR2": {
            "name": "npr2",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Normalized principal moments ratio 2 (=I2/I3)",
        },
    },
    "2D-Descriptors": {
        # Feature names are extracted from rdkit.Chem.Descriptors.descList
        "MaxEStateIndex": {
            "name": "max_e_state_index",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Maximum value of the electrotopological state atom index",
        },
        "MinEStateIndex": {
            "name": "min_e_state_index",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Minimum value of the electrotopological state atom index",
        },
        "MaxAbsEStateIndex": {
            "name": "max_abs_e_state_index",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": (
                "Maximum absolute value of the electrotopological state atom index"
            ),
        },
        "MinAbsEStateIndex": {
            "name": "min_abs_e_state_index",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": (
                "Minimum absolute value of the electrotopological state atom index"
            ),
        },
        "qed": {
            "name": "qed",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Quantitative estimation of drug-likeness",
        },
        "MolWt": {
            "name": "mol_wt",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Average molecular weight",
        },
        "HeavyAtomMolWt": {
            "name": "heavy_atom_mol_wt",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Average molecular weight ignoring hydrogens",
        },
        "ExactMolWt": {
            "name": "exact_mol_wt",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "The exact molecular weight",
        },
        "NumValenceElectrons": {
            "name": "num_valence_electrons",
            "dimensionality": "scalar",
            "type": "int",
            "units": "",
            "description": "The number of valence electrons in the molecule",
        },
        "NumRadicalElectrons": {
            "name": "num_radical_electrons",
            "dimensionality": "scalar",
            "type": "int",
            "units": "",
            "description": "The number of radical electrons in the molecule (regardless of their spin)",
        },
        "MaxPartialCharge": {
            "name": "max_partial_charge",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Maximum partial charge on the molecule",
        },
        "MinPartialCharge": {
            "name": "min_partial_charge",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Minimum partial charge on the molecule",
        },
        "MaxAbsPartialCharge": {
            "name": "max_abs_partial_charge",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Maximum absolute value of partial charge on the molecule",
        },
        "MinAbsPartialCharge": {
            "name": "min_abs_partial_charge",
            "dimensionality": "scalar",
            "type": "float",
            "units": "a.u.",
            "description": "Minimum absolute value of partial charge on the molecule",
        },
        "FpDensityMorgan1": {
            "name": "fp_density_morgan1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Morgan-1 density fingerprint",
        },
        "FpDensityMorgan2": {
            "name": "fp_density_morgan2",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Morgan-2 density fingerprint",
        },
        "FpDensityMorgan3": {
            "name": "fp_density_morgan3",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Morgan-3 density fingerprint",
        },
        "BCUT2D_MWHI": {
            "name": "bcut2d_mwhi",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_MWLOW": {
            "name": "bcut2d_mwlow",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_CHGHI": {
            "name": "bcut2d_chghi",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_CHGLO": {
            "name": "bcut2d_chglo",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_LOGPHI": {
            "name": "bcut2d_logphi",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_LOGPLOW": {
            "name": "bcut2d_logplow",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_LOGPLOW": {
            "name": "bcut2d_logplow",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_MRHI": {
            "name": "bcut2d_mrhi",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BCUT2D_MRLOW": {
            "name": "bcut2d_mrlow",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "BalabanJ": {
            "name": "balaban_j",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Balaban's J value for a molecule",
        },
        "BertzCT": {
            "name": "bertz_ct",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Topological complexity index of a molecule",
        },
        "Chi0": {
            "name": "chi0",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-0 graph descriptor",
        },
        "Chi0n": {
            "name": "chi0n",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-0n graph descriptor",
        },
        "Chi0v": {
            "name": "chi0v",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-0v graph descriptor",
        },
        "Chi1": {
            "name": "chi1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-1 graph descriptor",
        },
        "Chi1n": {
            "name": "chi1n",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-1n graph descriptor",
        },
        "Chi1v": {
            "name": "chi1v",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-1v graph descriptor",
        },
        "Chi2n": {
            "name": "chi2n",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-2n graph descriptor",
        },
        "Chi2v": {
            "name": "chi2v",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-2v graph descriptor",
        },
        "Chi3n": {
            "name": "chi3n",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-3n graph descriptor",
        },
        "Chi3v": {
            "name": "chi3v",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-3v graph descriptor",
        },
        "Chi4n": {
            "name": "chi4n",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-4n graph descriptor",
        },
        "Chi4v": {
            "name": "chi4v",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "Chi-4v graph descriptor",
        },
        "HallKierAlpha": {
            "name": "hall_kier_alpha",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "Ipc": {
            "name": "ipc",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": (
                "the information content of the coefficients of the characteristic"
                "polynomial of the adjacency matrix of a hydrogen-suppressed graph of a molecule"
            ),
        },
        "Kappa1": {
            "name": "kappa1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "Kappa2": {
            "name": "kappa2",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "Kappa3": {
            "name": "kappa3",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "LabuteASA": {
            "name": "labute_asa",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "PEOE_VSA1": {
            "name": "peoe_vsa1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-1 (-inf < x < -0.30)",
        },
        "PEOE_VSA10": {
            "name": "peoe_vsa10",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-10 ( 0.10 <= x <  0.15)",
        },
        "PEOE_VSA11": {
            "name": "peoe_vsa11",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-11 ( 0.15 <= x <  0.20)",
        },
        "PEOE_VSA12": {
            "name": "peoe_vsa12",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-12 ( 0.20 <= x <  0.25)",
        },
        "PEOE_VSA13": {
            "name": "peoe_vsa13",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-13 ( 0.25 <= x <  0.30)",
        },
        "PEOE_VSA14": {
            "name": "peoe_vsa14",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-14 ( 0.30 <= x < inf)",
        },
        "PEOE_VSA2": {
            "name": "peoe_vsa2",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-2 (-0.30 <= x < -0.25)",
        },
        "PEOE_VSA3": {
            "name": "peoe_vsa3",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-3 (-0.25 <= x < -0.20)",
        },
        "PEOE_VSA4": {
            "name": "peoe_vsa4",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-4 (-0.20 <= x < -0.15)",
        },
        "PEOE_VSA5": {
            "name": "peoe_vsa5",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-5 (-0.15 <= x < -0.10)",
        },
        "PEOE_VSA6": {
            "name": "peoe_vsa6",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-6 (-0.10 <= x < -0.05)",
        },
        "PEOE_VSA7": {
            "name": "peoe_vsa7",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-7 (-0.05 <= x <  0.00)",
        },
        "PEOE_VSA8": {
            "name": "peoe_vsa8",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-8 ( 0.00 <= x <  0.05)",
        },
        "PEOE_VSA9": {
            "name": "peoe_vsa9",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE Charge VSA Descriptor-9 ( 0.05 <= x <  0.10)",
        },
        "SMR_VSA1": {
            "name": "smr_vsa1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE MR VSA Descriptor-1 (-inf < x <  1.29)",
        },
        "SMR_VSA10": {
            "name": "smr_vsa10",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE MR VSA Descriptor-10 ( 4.00 <= x < inf)",
        },
        "SMR_VSA1": {
            "name": "smr_vsa1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },
        "SMR_VSA2": {
            "name": "smr_vsa2",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE MR VSA Descriptor-2 ( 1.29 <= x <  1.82)",
        },
        "SMR_VSA3": {
            "name": "smr_vsa3",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE MR VSA Descriptor-3 ( 1.82 <= x <  2.24)",
        },
        "SMR_VSA4": {
            "name": "smr_vsa4",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE MR VSA Descriptor-4 ( 2.24 <= x <  2.45)",
        },
        "SMR_VSA5": {
            "name": "smr_vsa5",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE MR VSA Descriptor-5 ( 2.45 <= x <  2.75)",
        },
        "SMR_VSA6": {
            "name": "smr_vsa6",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE MR VSA Descriptor-6 ( 2.75 <= x <  3.05)",
        },
        "SMR_VSA7": {
            "name": "smr_vsa7",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "MOE MR VSA Descriptor-7 ( 3.05 <= x <  3.63)",
        },
        "SMR_VSA1": {
            "name": "smr_vsa1",
            "dimensionality": "scalar",
            "type": "float",
            "units": "",
            "description": "",
        },

    },
}
